/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppHistoriqueRouteImport } from './routes/_app.historique'
import { Route as AppDbAdminRouteImport } from './routes/_app.db-admin'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppCatalogueRouteImport } from './routes/_app.catalogue'
import { Route as AppCaisseRouteImport } from './routes/_app.caisse'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppDbAdminRoute = AppDbAdminRouteImport.update({
  id: '/db-admin',
  path: '/db-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueRoute = AppCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AppRoute,
} as any)
const AppCaisseRoute = AppCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/caisse': typeof AppCaisseRoute
  '/catalogue': typeof AppCatalogueRoute
  '/clients': typeof AppClientsRoute
  '/db-admin': typeof AppDbAdminRoute
  '/historique': typeof AppHistoriqueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AppAgendaRoute
  '/caisse': typeof AppCaisseRoute
  '/catalogue': typeof AppCatalogueRoute
  '/clients': typeof AppClientsRoute
  '/db-admin': typeof AppDbAdminRoute
  '/historique': typeof AppHistoriqueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/caisse': typeof AppCaisseRoute
  '/_app/catalogue': typeof AppCatalogueRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/db-admin': typeof AppDbAdminRoute
  '/_app/historique': typeof AppHistoriqueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/caisse'
    | '/catalogue'
    | '/clients'
    | '/db-admin'
    | '/historique'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/caisse'
    | '/catalogue'
    | '/clients'
    | '/db-admin'
    | '/historique'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/agenda'
    | '/_app/caisse'
    | '/_app/catalogue'
    | '/_app/clients'
    | '/_app/db-admin'
    | '/_app/historique'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/historique': {
      id: '/_app/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db-admin': {
      id: '/_app/db-admin'
      path: '/db-admin'
      fullPath: '/db-admin'
      preLoaderRoute: typeof AppDbAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue': {
      id: '/_app/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AppCatalogueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caisse': {
      id: '/_app/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof AppCaisseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppCaisseRoute: typeof AppCaisseRoute
  AppCatalogueRoute: typeof AppCatalogueRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDbAdminRoute: typeof AppDbAdminRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppCaisseRoute: AppCaisseRoute,
  AppCatalogueRoute: AppCatalogueRoute,
  AppClientsRoute: AppClientsRoute,
  AppDbAdminRoute: AppDbAdminRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
