/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalleAttenteRouteImport } from './routes/salle-attente'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentreSlugRouteImport } from './routes/centre.$slug'
import { Route as AppTicketsRouteImport } from './routes/_app.tickets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppHistoriqueRouteImport } from './routes/_app.historique'
import { Route as AppGuideStageRouteImport } from './routes/_app.guide-stage'
import { Route as AppDbAdminRouteImport } from './routes/_app.db-admin'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCrmRouteImport } from './routes/_app.crm'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppCatalogueRouteImport } from './routes/_app.catalogue'
import { Route as AppCaisseRouteImport } from './routes/_app.caisse'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppAdminTenantsRouteImport } from './routes/_app.admin-tenants'
import { Route as AppAccessLogsRouteImport } from './routes/_app.access-logs'

const SalleAttenteRoute = SalleAttenteRouteImport.update({
  id: '/salle-attente',
  path: '/salle-attente',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentreSlugRoute = CentreSlugRouteImport.update({
  id: '/centre/$slug',
  path: '/centre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideStageRoute = AppGuideStageRouteImport.update({
  id: '/guide-stage',
  path: '/guide-stage',
  getParentRoute: () => AppRoute,
} as any)
const AppDbAdminRoute = AppDbAdminRouteImport.update({
  id: '/db-admin',
  path: '/db-admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogueRoute = AppCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AppRoute,
} as any)
const AppCaisseRoute = AppCaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsRoute = AppAdminTenantsRouteImport.update({
  id: '/admin-tenants',
  path: '/admin-tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppAccessLogsRoute = AppAccessLogsRouteImport.update({
  id: '/access-logs',
  path: '/access-logs',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/salle-attente': typeof SalleAttenteRoute
  '/access-logs': typeof AppAccessLogsRoute
  '/admin-tenants': typeof AppAdminTenantsRoute
  '/agenda': typeof AppAgendaRoute
  '/caisse': typeof AppCaisseRoute
  '/catalogue': typeof AppCatalogueRoute
  '/clients': typeof AppClientsRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/db-admin': typeof AppDbAdminRoute
  '/guide-stage': typeof AppGuideStageRoute
  '/historique': typeof AppHistoriqueRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRoute
  '/centre/$slug': typeof CentreSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/salle-attente': typeof SalleAttenteRoute
  '/access-logs': typeof AppAccessLogsRoute
  '/admin-tenants': typeof AppAdminTenantsRoute
  '/agenda': typeof AppAgendaRoute
  '/caisse': typeof AppCaisseRoute
  '/catalogue': typeof AppCatalogueRoute
  '/clients': typeof AppClientsRoute
  '/crm': typeof AppCrmRoute
  '/dashboard': typeof AppDashboardRoute
  '/db-admin': typeof AppDbAdminRoute
  '/guide-stage': typeof AppGuideStageRoute
  '/historique': typeof AppHistoriqueRoute
  '/settings': typeof AppSettingsRoute
  '/tickets': typeof AppTicketsRoute
  '/centre/$slug': typeof CentreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/salle-attente': typeof SalleAttenteRoute
  '/_app/access-logs': typeof AppAccessLogsRoute
  '/_app/admin-tenants': typeof AppAdminTenantsRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/caisse': typeof AppCaisseRoute
  '/_app/catalogue': typeof AppCatalogueRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/crm': typeof AppCrmRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/db-admin': typeof AppDbAdminRoute
  '/_app/guide-stage': typeof AppGuideStageRoute
  '/_app/historique': typeof AppHistoriqueRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tickets': typeof AppTicketsRoute
  '/centre/$slug': typeof CentreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/salle-attente'
    | '/access-logs'
    | '/admin-tenants'
    | '/agenda'
    | '/caisse'
    | '/catalogue'
    | '/clients'
    | '/crm'
    | '/dashboard'
    | '/db-admin'
    | '/guide-stage'
    | '/historique'
    | '/settings'
    | '/tickets'
    | '/centre/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/salle-attente'
    | '/access-logs'
    | '/admin-tenants'
    | '/agenda'
    | '/caisse'
    | '/catalogue'
    | '/clients'
    | '/crm'
    | '/dashboard'
    | '/db-admin'
    | '/guide-stage'
    | '/historique'
    | '/settings'
    | '/tickets'
    | '/centre/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/pricing'
    | '/salle-attente'
    | '/_app/access-logs'
    | '/_app/admin-tenants'
    | '/_app/agenda'
    | '/_app/caisse'
    | '/_app/catalogue'
    | '/_app/clients'
    | '/_app/crm'
    | '/_app/dashboard'
    | '/_app/db-admin'
    | '/_app/guide-stage'
    | '/_app/historique'
    | '/_app/settings'
    | '/_app/tickets'
    | '/centre/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SalleAttenteRoute: typeof SalleAttenteRoute
  CentreSlugRoute: typeof CentreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salle-attente': {
      id: '/salle-attente'
      path: '/salle-attente'
      fullPath: '/salle-attente'
      preLoaderRoute: typeof SalleAttenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centre/$slug': {
      id: '/centre/$slug'
      path: '/centre/$slug'
      fullPath: '/centre/$slug'
      preLoaderRoute: typeof CentreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tickets': {
      id: '/_app/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historique': {
      id: '/_app/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guide-stage': {
      id: '/_app/guide-stage'
      path: '/guide-stage'
      fullPath: '/guide-stage'
      preLoaderRoute: typeof AppGuideStageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db-admin': {
      id: '/_app/db-admin'
      path: '/db-admin'
      fullPath: '/db-admin'
      preLoaderRoute: typeof AppDbAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm': {
      id: '/_app/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogue': {
      id: '/_app/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AppCatalogueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/caisse': {
      id: '/_app/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof AppCaisseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-tenants': {
      id: '/_app/admin-tenants'
      path: '/admin-tenants'
      fullPath: '/admin-tenants'
      preLoaderRoute: typeof AppAdminTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/access-logs': {
      id: '/_app/access-logs'
      path: '/access-logs'
      fullPath: '/access-logs'
      preLoaderRoute: typeof AppAccessLogsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccessLogsRoute: typeof AppAccessLogsRoute
  AppAdminTenantsRoute: typeof AppAdminTenantsRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppCaisseRoute: typeof AppCaisseRoute
  AppCatalogueRoute: typeof AppCatalogueRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDbAdminRoute: typeof AppDbAdminRoute
  AppGuideStageRoute: typeof AppGuideStageRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTicketsRoute: typeof AppTicketsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessLogsRoute: AppAccessLogsRoute,
  AppAdminTenantsRoute: AppAdminTenantsRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppCaisseRoute: AppCaisseRoute,
  AppCatalogueRoute: AppCatalogueRoute,
  AppClientsRoute: AppClientsRoute,
  AppCrmRoute: AppCrmRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDbAdminRoute: AppDbAdminRoute,
  AppGuideStageRoute: AppGuideStageRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTicketsRoute: AppTicketsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SalleAttenteRoute: SalleAttenteRoute,
  CentreSlugRoute: CentreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
